// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GeminiService Gemini 配置管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddProvider 添加供应商
 */
export function AddProvider(provider: $models.GeminiProvider): $CancellablePromise<void> {
    return $Call.ByID(2833198257, provider);
}

/**
 * ApplySingleProvider 直连应用单一供应商（别名，统一 API 命名）
 * 与 SwitchProvider 功能相同，仅在代理关闭时可用
 */
export function ApplySingleProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3103860642, id);
}

/**
 * CreateProviderFromPreset 从预设创建供应商
 */
export function CreateProviderFromPreset(presetName: string, apiKey: string): $CancellablePromise<$models.GeminiProvider | null> {
    return $Call.ByID(974856947, presetName, apiKey).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteProvider 删除供应商
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(758292695, id);
}

/**
 * DisableProxy 禁用代理（手术式撤销：仅移除注入的代理配置，保留用户其他编辑）
 */
export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(1809533069);
}

/**
 * DuplicateProvider 复制供应商
 */
export function DuplicateProvider(sourceID: string): $CancellablePromise<$models.GeminiProvider | null> {
    return $Call.ByID(159215875, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * EnableProxy 启用代理
 */
export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(3882720282);
}

/**
 * GetDirectAppliedProviderID 返回当前直连应用的 Provider ID
 * 通过读取 CLI 配置文件反推当前使用的 provider
 * 返回值：
 *   - nil: 配置指向本地代理 或 无法匹配到 provider
 *   - *string: 匹配到的 provider ID
 */
export function GetDirectAppliedProviderID(): $CancellablePromise<string | null> {
    return $Call.ByID(1240445803);
}

/**
 * GetPresets 获取预设供应商列表
 */
export function GetPresets(): $CancellablePromise<$models.GeminiPreset[]> {
    return $Call.ByID(2578586649).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetProviders 获取已配置的供应商列表
 */
export function GetProviders(): $CancellablePromise<$models.GeminiProvider[]> {
    return $Call.ByID(4102812223).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetStatus 获取当前 Gemini 配置状态
 */
export function GetStatus(): $CancellablePromise<$models.GeminiStatus | null> {
    return $Call.ByID(278805041).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ProxyStatus 获取代理状态
 */
export function ProxyStatus(): $CancellablePromise<$models.GeminiProxyStatus | null> {
    return $Call.ByID(615836637).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ReorderProviders 重新排序供应商（按传入的 ID 顺序）
 */
export function ReorderProviders(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(1005362802, ids);
}

/**
 * Start Wails生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2631735887);
}

/**
 * Stop Wails生命周期方法
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(303555861);
}

/**
 * SwitchProvider 切换到指定供应商
 * 注意：代理启用时禁止切换（与 Claude/Codex 保持一致）
 */
export function SwitchProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3824145224, id);
}

/**
 * UpdateProvider 更新供应商
 */
export function UpdateProvider(provider: $models.GeminiProvider): $CancellablePromise<void> {
    return $Call.ByID(2675358193, provider);
}

// Private type creation functions
const $$createType0 = $models.GeminiProvider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GeminiPreset.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.GeminiStatus.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.GeminiProxyStatus.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
