// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function HeatmapStats(days: number): $CancellablePromise<$models.HeatmapStat[]> {
    return $Call.ByID(1056815029, days).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListProviders(platform: string): $CancellablePromise<string[]> {
    return $Call.ByID(790916236, platform).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListProvidersOnDate(platform: string, date: string): $CancellablePromise<string[]> {
    return $Call.ByID(3732269833, platform, date).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListRequestLogs(platform: string, provider: string, limit: number): $CancellablePromise<$models.ReqeustLog[]> {
    return $Call.ByID(1199056012, platform, provider, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListRequestLogsOnDate(platform: string, provider: string, date: string, limit: number): $CancellablePromise<$models.ReqeustLog[]> {
    return $Call.ByID(1718346505, platform, provider, date, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ProviderDailyStats(platform: string): $CancellablePromise<$models.ProviderDailyStat[]> {
    return $Call.ByID(974013659, platform).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ProviderDailyStatsOnDate(platform: string, date: string): $CancellablePromise<$models.ProviderDailyStat[]> {
    return $Call.ByID(4059554018, platform, date).then(($result: any) => {
        return $$createType6($result);
    });
}

export function RunRetentionCleanup(): $CancellablePromise<number> {
    return $Call.ByID(523191977);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(567661822);
}

export function StatsOnDate(platform: string, date: string): $CancellablePromise<$models.LogStats> {
    return $Call.ByID(95318484, platform, date).then(($result: any) => {
        return $$createType7($result);
    });
}

export function StatsSince(platform: string): $CancellablePromise<$models.LogStats> {
    return $Call.ByID(2831143405, platform).then(($result: any) => {
        return $$createType7($result);
    });
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2614024838);
}

// Private type creation functions
const $$createType0 = $models.HeatmapStat.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.ReqeustLog.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ProviderDailyStat.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.LogStats.createFrom;
