// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AppSettings {
    "show_heatmap": boolean;
    "show_home_title": boolean;
    "auto_start": boolean;
    "auto_update": boolean;
    "auto_connectivity_test": boolean;

    /**
     * 供应商切换通知开关
     */
    "enable_switch_notify": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("show_heatmap" in $$source)) {
            this["show_heatmap"] = false;
        }
        if (!("show_home_title" in $$source)) {
            this["show_home_title"] = false;
        }
        if (!("auto_start" in $$source)) {
            this["auto_start"] = false;
        }
        if (!("auto_update" in $$source)) {
            this["auto_update"] = false;
        }
        if (!("auto_connectivity_test" in $$source)) {
            this["auto_connectivity_test"] = false;
        }
        if (!("enable_switch_notify" in $$source)) {
            this["enable_switch_notify"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * BlacklistLevelConfig 等级拉黑配置（v0.4.0 新增）
 */
export class BlacklistLevelConfig {
    /**
     * 功能开关
     * 是否启用等级拉黑
     */
    "enableLevelBlacklist": boolean;

    /**
     * 基础配置
     * 失败阈值（连续失败次数）
     */
    "failureThreshold": number;

    /**
     * 去重窗口（秒）
     */
    "dedupeWindowSeconds": number;

    /**
     * 降级配置
     * 正常降级间隔（小时）
     */
    "normalDegradeIntervalHours": number;

    /**
     * 宽恕触发时间（小时）
     */
    "forgivenessHours": number;

    /**
     * 跳级惩罚窗口（小时）
     */
    "jumpPenaltyWindowHours": number;

    /**
     * 等级时长配置（分钟）
     * L1 拉黑时长
     */
    "l1DurationMinutes": number;

    /**
     * L2 拉黑时长
     */
    "l2DurationMinutes": number;

    /**
     * L3 拉黑时长
     */
    "l3DurationMinutes": number;

    /**
     * L4 拉黑时长
     */
    "l4DurationMinutes": number;

    /**
     * L5 拉黑时长
     */
    "l5DurationMinutes": number;

    /**
     * 开关关闭时的行为
     * fixed=固定拉黑, none=不拉黑
     */
    "fallbackMode": string;

    /**
     * 固定拉黑时长（分钟）
     */
    "fallbackDurationMinutes": number;

    /** Creates a new BlacklistLevelConfig instance. */
    constructor($$source: Partial<BlacklistLevelConfig> = {}) {
        if (!("enableLevelBlacklist" in $$source)) {
            this["enableLevelBlacklist"] = false;
        }
        if (!("failureThreshold" in $$source)) {
            this["failureThreshold"] = 0;
        }
        if (!("dedupeWindowSeconds" in $$source)) {
            this["dedupeWindowSeconds"] = 0;
        }
        if (!("normalDegradeIntervalHours" in $$source)) {
            this["normalDegradeIntervalHours"] = 0;
        }
        if (!("forgivenessHours" in $$source)) {
            this["forgivenessHours"] = 0;
        }
        if (!("jumpPenaltyWindowHours" in $$source)) {
            this["jumpPenaltyWindowHours"] = 0;
        }
        if (!("l1DurationMinutes" in $$source)) {
            this["l1DurationMinutes"] = 0;
        }
        if (!("l2DurationMinutes" in $$source)) {
            this["l2DurationMinutes"] = 0;
        }
        if (!("l3DurationMinutes" in $$source)) {
            this["l3DurationMinutes"] = 0;
        }
        if (!("l4DurationMinutes" in $$source)) {
            this["l4DurationMinutes"] = 0;
        }
        if (!("l5DurationMinutes" in $$source)) {
            this["l5DurationMinutes"] = 0;
        }
        if (!("fallbackMode" in $$source)) {
            this["fallbackMode"] = "";
        }
        if (!("fallbackDurationMinutes" in $$source)) {
            this["fallbackDurationMinutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlacklistLevelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BlacklistLevelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlacklistLevelConfig($$parsedSource as Partial<BlacklistLevelConfig>);
    }
}

/**
 * BlacklistSettings 黑名单配置（基础配置，向后兼容）
 */
export class BlacklistSettings {
    /**
     * 失败次数阈值
     */
    "failureThreshold": number;

    /**
     * 拉黑时长（分钟）
     */
    "durationMinutes": number;

    /** Creates a new BlacklistSettings instance. */
    constructor($$source: Partial<BlacklistSettings> = {}) {
        if (!("failureThreshold" in $$source)) {
            this["failureThreshold"] = 0;
        }
        if (!("durationMinutes" in $$source)) {
            this["durationMinutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlacklistSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): BlacklistSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlacklistSettings($$parsedSource as Partial<BlacklistSettings>);
    }
}

/**
 * BlacklistStatus 黑名单状态（用于前端展示）
 */
export class BlacklistStatus {
    "platform": string;
    "providerName": string;
    "failureCount": number;
    "blacklistedAt": time$0.Time | null;
    "blacklistedUntil": time$0.Time | null;
    "lastFailureAt": time$0.Time | null;
    "isBlacklisted": boolean;

    /**
     * 剩余拉黑时间（秒）
     */
    "remainingSeconds": number;

    /**
     * v0.4.0 新增：等级拉黑相关字段
     * 当前黑名单等级 (0-5)
     */
    "blacklistLevel": number;

    /**
     * 最后恢复时间
     */
    "lastRecoveredAt": time$0.Time | null;

    /**
     * 距离宽恕还剩多少秒（3小时倒计时）
     */
    "forgivenessRemaining": number;

    /** Creates a new BlacklistStatus instance. */
    constructor($$source: Partial<BlacklistStatus> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("providerName" in $$source)) {
            this["providerName"] = "";
        }
        if (!("failureCount" in $$source)) {
            this["failureCount"] = 0;
        }
        if (!("blacklistedAt" in $$source)) {
            this["blacklistedAt"] = null;
        }
        if (!("blacklistedUntil" in $$source)) {
            this["blacklistedUntil"] = null;
        }
        if (!("lastFailureAt" in $$source)) {
            this["lastFailureAt"] = null;
        }
        if (!("isBlacklisted" in $$source)) {
            this["isBlacklisted"] = false;
        }
        if (!("remainingSeconds" in $$source)) {
            this["remainingSeconds"] = 0;
        }
        if (!("blacklistLevel" in $$source)) {
            this["blacklistLevel"] = 0;
        }
        if (!("lastRecoveredAt" in $$source)) {
            this["lastRecoveredAt"] = null;
        }
        if (!("forgivenessRemaining" in $$source)) {
            this["forgivenessRemaining"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlacklistStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BlacklistStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlacklistStatus($$parsedSource as Partial<BlacklistStatus>);
    }
}

/**
 * CLIConfig CLI 配置数据
 */
export class CLIConfig {
    "platform": CLIPlatform;
    "fields": CLIConfigField[];

    /**
     * 原始文件内容（用于高级编辑）
     */
    "rawContent"?: string;

    /**
     * 多文件内容预览
     */
    "rawFiles"?: CLIConfigFile[];

    /**
     * "json" 或 "toml"
     */
    "configFormat"?: string;

    /**
     * Gemini .env 内容
     */
    "envContent"?: { [_: string]: string };

    /**
     * 配置文件路径
     */
    "filePath"?: string;

    /**
     * 可编辑字段的当前值
     */
    "editable"?: { [_: string]: any };

    /** Creates a new CLIConfig instance. */
    constructor($$source: Partial<CLIConfig> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = CLIPlatform.$zero;
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIConfig {
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        if ("rawFiles" in $$parsedSource) {
            $$parsedSource["rawFiles"] = $$createField3_0($$parsedSource["rawFiles"]);
        }
        if ("envContent" in $$parsedSource) {
            $$parsedSource["envContent"] = $$createField5_0($$parsedSource["envContent"]);
        }
        if ("editable" in $$parsedSource) {
            $$parsedSource["editable"] = $$createField7_0($$parsedSource["editable"]);
        }
        return new CLIConfig($$parsedSource as Partial<CLIConfig>);
    }
}

/**
 * CLIConfigField 配置字段信息
 */
export class CLIConfigField {
    "key": string;
    "value": string;
    "locked": boolean;
    "hint"?: string;

    /**
     * "string", "boolean", "object"
     */
    "type": string;
    "required"?: boolean;

    /** Creates a new CLIConfigField instance. */
    constructor($$source: Partial<CLIConfigField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIConfigField instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIConfigField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIConfigField($$parsedSource as Partial<CLIConfigField>);
    }
}

/**
 * CLIConfigFile 配置文件预览（用于前端显示原始内容）
 */
export class CLIConfigFile {
    "path": string;

    /**
     * "json", "toml", "env"
     */
    "format"?: string;
    "content": string;

    /** Creates a new CLIConfigFile instance. */
    constructor($$source: Partial<CLIConfigFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIConfigFile instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIConfigFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIConfigFile($$parsedSource as Partial<CLIConfigFile>);
    }
}

/**
 * CLIPlatform CLI 平台类型
 */
export enum CLIPlatform {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlatformClaude = "claude",
    PlatformCodex = "codex",
    PlatformGemini = "gemini",
};

/**
 * CLITemplate CLI 配置模板
 */
export class CLITemplate {
    "template": { [_: string]: any };
    "isGlobalDefault": boolean;

    /** Creates a new CLITemplate instance. */
    constructor($$source: Partial<CLITemplate> = {}) {
        if (!("template" in $$source)) {
            this["template"] = {};
        }
        if (!("isGlobalDefault" in $$source)) {
            this["isGlobalDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLITemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): CLITemplate {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("template" in $$parsedSource) {
            $$parsedSource["template"] = $$createField0_0($$parsedSource["template"]);
        }
        return new CLITemplate($$parsedSource as Partial<CLITemplate>);
    }
}

export class ClaudeProxyStatus {
    "enabled": boolean;
    "base_url": string;

    /** Creates a new ClaudeProxyStatus instance. */
    constructor($$source: Partial<ClaudeProxyStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeProxyStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaudeProxyStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeProxyStatus($$parsedSource as Partial<ClaudeProxyStatus>);
    }
}

export class ConfigImportResult {
    "status": ConfigImportStatus;
    "imported_providers": number;
    "imported_mcp": number;

    /** Creates a new ConfigImportResult instance. */
    constructor($$source: Partial<ConfigImportResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new ConfigImportStatus());
        }
        if (!("imported_providers" in $$source)) {
            this["imported_providers"] = 0;
        }
        if (!("imported_mcp" in $$source)) {
            this["imported_mcp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigImportResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        return new ConfigImportResult($$parsedSource as Partial<ConfigImportResult>);
    }
}

export class ConfigImportStatus {
    "config_exists": boolean;
    "config_path"?: string;
    "pending_providers": boolean;
    "pending_mcp": boolean;
    "pending_provider_count": number;
    "pending_mcp_count": number;

    /** Creates a new ConfigImportStatus instance. */
    constructor($$source: Partial<ConfigImportStatus> = {}) {
        if (!("config_exists" in $$source)) {
            this["config_exists"] = false;
        }
        if (!("pending_providers" in $$source)) {
            this["pending_providers"] = false;
        }
        if (!("pending_mcp" in $$source)) {
            this["pending_mcp"] = false;
        }
        if (!("pending_provider_count" in $$source)) {
            this["pending_provider_count"] = 0;
        }
        if (!("pending_mcp_count" in $$source)) {
            this["pending_mcp_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigImportStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigImportStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigImportStatus($$parsedSource as Partial<ConfigImportStatus>);
    }
}

/**
 * ConnectivityResult 连通性测试结果
 */
export class ConnectivityResult {
    "providerId": number;
    "providerName": string;
    "platform": string;
    "status": number;
    "subStatus": string;
    "latencyMs": number;
    "lastChecked": time$0.Time;
    "message"?: string;
    "httpCode"?: number;

    /** Creates a new ConnectivityResult instance. */
    constructor($$source: Partial<ConnectivityResult> = {}) {
        if (!("providerId" in $$source)) {
            this["providerId"] = 0;
        }
        if (!("providerName" in $$source)) {
            this["providerName"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("subStatus" in $$source)) {
            this["subStatus"] = "";
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("lastChecked" in $$source)) {
            this["lastChecked"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectivityResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectivityResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectivityResult($$parsedSource as Partial<ConnectivityResult>);
    }
}

/**
 * ConsoleLog 控制台日志条目
 */
export class ConsoleLog {
    "timestamp": time$0.Time;

    /**
     * INFO, WARN, ERROR
     */
    "level": string;
    "message": string;

    /** Creates a new ConsoleLog instance. */
    constructor($$source: Partial<ConsoleLog> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsoleLog instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsoleLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsoleLog($$parsedSource as Partial<ConsoleLog>);
    }
}

/**
 * DeepLinkImportRequest 深度链接导入请求模型
 */
export class DeepLinkImportRequest {
    /**
     * 协议版本 (e.g., "v1")
     */
    "version": string;

    /**
     * 资源类型 (e.g., "provider")
     */
    "resource": string;

    /**
     * 目标应用 (claude/codex/gemini)
     */
    "app": string;

    /**
     * 供应商名称
     */
    "name": string;

    /**
     * 供应商主页
     */
    "homepage": string;

    /**
     * API 端点
     */
    "endpoint": string;

    /**
     * API 密钥
     */
    "apiKey": string;

    /**
     * 可选模型名称
     */
    "model"?: string | null;

    /**
     * 可选备注
     */
    "notes"?: string | null;

    /**
     * Claude Haiku 模型
     */
    "haikuModel"?: string | null;

    /**
     * Claude Sonnet 模型
     */
    "sonnetModel"?: string | null;

    /**
     * Claude Opus 模型
     */
    "opusModel"?: string | null;

    /**
     * Base64 编码的配置
     */
    "config"?: string | null;

    /**
     * 配置格式 (json/toml)
     */
    "configFormat"?: string | null;

    /**
     * 远程配置 URL
     */
    "configUrl"?: string | null;

    /** Creates a new DeepLinkImportRequest instance. */
    constructor($$source: Partial<DeepLinkImportRequest> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("app" in $$source)) {
            this["app"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeepLinkImportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeepLinkImportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeepLinkImportRequest($$parsedSource as Partial<DeepLinkImportRequest>);
    }
}

/**
 * EndpointLatency 端点延迟测试结果
 */
export class EndpointLatency {
    /**
     * 端点 URL
     */
    "url": string;

    /**
     * 延迟（毫秒），nil 表示失败
     */
    "latency": number | null;

    /**
     * HTTP 状态码
     */
    "status"?: number | null;

    /**
     * 错误信息
     */
    "error"?: string | null;

    /** Creates a new EndpointLatency instance. */
    constructor($$source: Partial<EndpointLatency> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("latency" in $$source)) {
            this["latency"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointLatency instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointLatency {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointLatency($$parsedSource as Partial<EndpointLatency>);
    }
}

/**
 * EnvConflict 环境变量冲突
 */
export class EnvConflict {
    /**
     * 变量名
     */
    "varName": string;

    /**
     * 变量值
     */
    "varValue": string;

    /**
     * 来源类型: "system" | "file"
     */
    "sourceType": string;

    /**
     * 来源路径
     */
    "sourcePath": string;

    /** Creates a new EnvConflict instance. */
    constructor($$source: Partial<EnvConflict> = {}) {
        if (!("varName" in $$source)) {
            this["varName"] = "";
        }
        if (!("varValue" in $$source)) {
            this["varValue"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvConflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvConflict($$parsedSource as Partial<EnvConflict>);
    }
}

/**
 * GeminiAuthType 认证类型
 */
export enum GeminiAuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Google 官方 OAuth
     */
    GeminiAuthOAuth = "oauth-personal",

    /**
     * API Key 认证
     */
    GeminiAuthAPIKey = "gemini-api-key",

    /**
     * PackyCode 合作方
     */
    GeminiAuthPackycode = "packycode",

    /**
     * 通用第三方
     */
    GeminiAuthGeneric = "generic",
};

/**
 * GeminiPreset 预设供应商
 */
export class GeminiPreset {
    "name": string;
    "websiteUrl": string;
    "apiKeyUrl"?: string;
    "baseUrl"?: string;
    "model"?: string;
    "description"?: string;
    "category": string;
    "partnerPromotionKey"?: string;
    "envConfig"?: { [_: string]: string };

    /** Creates a new GeminiPreset instance. */
    constructor($$source: Partial<GeminiPreset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("websiteUrl" in $$source)) {
            this["websiteUrl"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeminiPreset instance from a string or object.
     */
    static createFrom($$source: any = {}): GeminiPreset {
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("envConfig" in $$parsedSource) {
            $$parsedSource["envConfig"] = $$createField8_0($$parsedSource["envConfig"]);
        }
        return new GeminiPreset($$parsedSource as Partial<GeminiPreset>);
    }
}

/**
 * GeminiProvider Gemini 供应商配置
 */
export class GeminiProvider {
    "id": string;
    "name": string;
    "websiteUrl"?: string;
    "apiKeyUrl"?: string;
    "baseUrl"?: string;
    "apiKey"?: string;
    "model"?: string;
    "description"?: string;

    /**
     * official, third_party, custom
     */
    "category"?: string;

    /**
     * 用于识别供应商类型
     */
    "partnerPromotionKey"?: string;
    "enabled": boolean;

    /**
     * 优先级分组 (1-10, 默认 1)
     */
    "level"?: number;

    /**
     * .env 配置
     */
    "envConfig"?: { [_: string]: string };

    /**
     * settings.json 配置
     */
    "settingsConfig"?: { [_: string]: any };

    /** Creates a new GeminiProvider instance. */
    constructor($$source: Partial<GeminiProvider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeminiProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): GeminiProvider {
        const $$createField12_0 = $$createType4;
        const $$createField13_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("envConfig" in $$parsedSource) {
            $$parsedSource["envConfig"] = $$createField12_0($$parsedSource["envConfig"]);
        }
        if ("settingsConfig" in $$parsedSource) {
            $$parsedSource["settingsConfig"] = $$createField13_0($$parsedSource["settingsConfig"]);
        }
        return new GeminiProvider($$parsedSource as Partial<GeminiProvider>);
    }
}

/**
 * GeminiProxyStatus Gemini 代理状态
 */
export class GeminiProxyStatus {
    "enabled": boolean;
    "base_url": string;

    /** Creates a new GeminiProxyStatus instance. */
    constructor($$source: Partial<GeminiProxyStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeminiProxyStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GeminiProxyStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeminiProxyStatus($$parsedSource as Partial<GeminiProxyStatus>);
    }
}

/**
 * GeminiStatus Gemini 配置状态
 */
export class GeminiStatus {
    "enabled": boolean;
    "currentProvider"?: string;
    "authType": GeminiAuthType;
    "hasApiKey": boolean;
    "hasBaseUrl": boolean;
    "model"?: string;

    /** Creates a new GeminiStatus instance. */
    constructor($$source: Partial<GeminiStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("authType" in $$source)) {
            this["authType"] = GeminiAuthType.$zero;
        }
        if (!("hasApiKey" in $$source)) {
            this["hasApiKey"] = false;
        }
        if (!("hasBaseUrl" in $$source)) {
            this["hasBaseUrl"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeminiStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GeminiStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeminiStatus($$parsedSource as Partial<GeminiStatus>);
    }
}

export class HeatmapStat {
    "day": string;
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "total_cost": number;

    /** Creates a new HeatmapStat instance. */
    constructor($$source: Partial<HeatmapStat> = {}) {
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("total_cost" in $$source)) {
            this["total_cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeatmapStat instance from a string or object.
     */
    static createFrom($$source: any = {}): HeatmapStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeatmapStat($$parsedSource as Partial<HeatmapStat>);
    }
}

export class Hotkey {
    /**
     * 热键ID
     */
    "id": number;

    /**
     * 键码
     */
    "keycode": number;

    /**
     * 修饰键
     */
    "modifiers": number;

    /** Creates a new Hotkey instance. */
    constructor($$source: Partial<Hotkey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("keycode" in $$source)) {
            this["keycode"] = 0;
        }
        if (!("modifiers" in $$source)) {
            this["modifiers"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hotkey instance from a string or object.
     */
    static createFrom($$source: any = {}): Hotkey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hotkey($$parsedSource as Partial<Hotkey>);
    }
}

export class LogStats {
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "cost_total": number;
    "cost_input": number;
    "cost_output": number;
    "cost_cache_create": number;
    "cost_cache_read": number;
    "series": LogStatsSeries[];

    /** Creates a new LogStats instance. */
    constructor($$source: Partial<LogStats> = {}) {
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("cost_total" in $$source)) {
            this["cost_total"] = 0;
        }
        if (!("cost_input" in $$source)) {
            this["cost_input"] = 0;
        }
        if (!("cost_output" in $$source)) {
            this["cost_output"] = 0;
        }
        if (!("cost_cache_create" in $$source)) {
            this["cost_cache_create"] = 0;
        }
        if (!("cost_cache_read" in $$source)) {
            this["cost_cache_read"] = 0;
        }
        if (!("series" in $$source)) {
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStats instance from a string or object.
     */
    static createFrom($$source: any = {}): LogStats {
        const $$createField11_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField11_0($$parsedSource["series"]);
        }
        return new LogStats($$parsedSource as Partial<LogStats>);
    }
}

export class LogStatsSeries {
    "day": string;
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "total_cost": number;

    /** Creates a new LogStatsSeries instance. */
    constructor($$source: Partial<LogStatsSeries> = {}) {
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("total_cost" in $$source)) {
            this["total_cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStatsSeries instance from a string or object.
     */
    static createFrom($$source: any = {}): LogStatsSeries {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogStatsSeries($$parsedSource as Partial<LogStatsSeries>);
    }
}

/**
 * MCPParseResult JSON 解析结果
 */
export class MCPParseResult {
    /**
     * 解析出的服务器列表
     */
    "servers": MCPServer[];

    /**
     * 与现有配置冲突的名称
     */
    "conflicts": string[];

    /**
     * 是否需要用户提供名称（单服务器无名时）
     */
    "needName": boolean;

    /** Creates a new MCPParseResult instance. */
    constructor($$source: Partial<MCPParseResult> = {}) {
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("needName" in $$source)) {
            this["needName"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPParseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPParseResult {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField0_0($$parsedSource["servers"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField1_0($$parsedSource["conflicts"]);
        }
        return new MCPParseResult($$parsedSource as Partial<MCPParseResult>);
    }
}

export class MCPServer {
    "name": string;
    "type": string;
    "command"?: string;
    "args"?: string[];
    "env"?: { [_: string]: string };
    "url"?: string;
    "website"?: string;
    "tips"?: string;
    "enable_platform": string[];
    "enabled_in_claude": boolean;
    "enabled_in_codex": boolean;
    "missing_placeholders": string[];

    /** Creates a new MCPServer instance. */
    constructor($$source: Partial<MCPServer> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("enable_platform" in $$source)) {
            this["enable_platform"] = [];
        }
        if (!("enabled_in_claude" in $$source)) {
            this["enabled_in_claude"] = false;
        }
        if (!("enabled_in_codex" in $$source)) {
            this["enabled_in_codex"] = false;
        }
        if (!("missing_placeholders" in $$source)) {
            this["missing_placeholders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServer instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPServer {
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType4;
        const $$createField8_0 = $$createType11;
        const $$createField11_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        if ("enable_platform" in $$parsedSource) {
            $$parsedSource["enable_platform"] = $$createField8_0($$parsedSource["enable_platform"]);
        }
        if ("missing_placeholders" in $$parsedSource) {
            $$parsedSource["missing_placeholders"] = $$createField11_0($$parsedSource["missing_placeholders"]);
        }
        return new MCPServer($$parsedSource as Partial<MCPServer>);
    }
}

/**
 * Prompt 自定义提示词
 */
export class Prompt {
    "id": string;
    "name": string;
    "content": string;
    "description"?: string | null;
    "enabled": boolean;
    "createdAt"?: number | null;
    "updatedAt"?: number | null;

    /** Creates a new Prompt instance. */
    constructor($$source: Partial<Prompt> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Prompt instance from a string or object.
     */
    static createFrom($$source: any = {}): Prompt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Prompt($$parsedSource as Partial<Prompt>);
    }
}

export class Provider {
    /**
     * 修复：使用 int64 支持大 ID 值
     */
    "id": number;
    "name": string;
    "apiUrl": string;
    "apiKey": string;
    "officialSite": string;
    "icon": string;
    "tint": string;
    "accent": string;
    "enabled": boolean;

    /**
     * 模型白名单 - Provider 原生支持的模型名
     * 使用 map 实现 O(1) 查找，向后兼容（omitempty）
     */
    "supportedModels"?: { [_: string]: boolean };

    /**
     * 模型映射 - 外部模型名 -> Provider 内部模型名
     * 支持精确匹配和通配符（如 "claude-*" -> "anthropic/claude-*"）
     */
    "modelMapping"?: { [_: string]: string };

    /**
     * 优先级分组 - 数字越小优先级越高（1-10，默认 1）
     * 使用 omitempty 确保零值不序列化，向后兼容
     */
    "level"?: number;

    /**
     * 连通性检测开关 - 是否启用自动连通性检测
     */
    "connectivityCheck"?: boolean;

    /** Creates a new Provider instance. */
    constructor($$source: Partial<Provider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("apiUrl" in $$source)) {
            this["apiUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("officialSite" in $$source)) {
            this["officialSite"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("tint" in $$source)) {
            this["tint"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     */
    static createFrom($$source: any = {}): Provider {
        const $$createField9_0 = $$createType12;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedModels" in $$parsedSource) {
            $$parsedSource["supportedModels"] = $$createField9_0($$parsedSource["supportedModels"]);
        }
        if ("modelMapping" in $$parsedSource) {
            $$parsedSource["modelMapping"] = $$createField10_0($$parsedSource["modelMapping"]);
        }
        return new Provider($$parsedSource as Partial<Provider>);
    }
}

export class ProviderDailyStat {
    "provider": string;
    "total_requests": number;
    "successful_requests": number;
    "failed_requests": number;
    "success_rate": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "cost_total": number;

    /** Creates a new ProviderDailyStat instance. */
    constructor($$source: Partial<ProviderDailyStat> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("successful_requests" in $$source)) {
            this["successful_requests"] = 0;
        }
        if (!("failed_requests" in $$source)) {
            this["failed_requests"] = 0;
        }
        if (!("success_rate" in $$source)) {
            this["success_rate"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("cost_total" in $$source)) {
            this["cost_total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderDailyStat instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderDailyStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderDailyStat($$parsedSource as Partial<ProviderDailyStat>);
    }
}

export class ReqeustLog {
    "id": number;

    /**
     * claude、codex 或 gemini
     */
    "platform": string;
    "model": string;

    /**
     * provider name
     */
    "provider": string;
    "http_code": number;
    "input_tokens": number;
    "output_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "reasoning_tokens": number;
    "is_stream": boolean;
    "duration_sec": number;
    "created_at": string;
    "input_cost": number;
    "output_cost": number;
    "reasoning_cost": number;
    "cache_create_cost": number;
    "cache_read_cost": number;
    "ephemeral_5m_cost": number;
    "ephemeral_1h_cost": number;
    "total_cost": number;
    "has_pricing": boolean;

    /** Creates a new ReqeustLog instance. */
    constructor($$source: Partial<ReqeustLog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("http_code" in $$source)) {
            this["http_code"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("is_stream" in $$source)) {
            this["is_stream"] = false;
        }
        if (!("duration_sec" in $$source)) {
            this["duration_sec"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("input_cost" in $$source)) {
            this["input_cost"] = 0;
        }
        if (!("output_cost" in $$source)) {
            this["output_cost"] = 0;
        }
        if (!("reasoning_cost" in $$source)) {
            this["reasoning_cost"] = 0;
        }
        if (!("cache_create_cost" in $$source)) {
            this["cache_create_cost"] = 0;
        }
        if (!("cache_read_cost" in $$source)) {
            this["cache_read_cost"] = 0;
        }
        if (!("ephemeral_5m_cost" in $$source)) {
            this["ephemeral_5m_cost"] = 0;
        }
        if (!("ephemeral_1h_cost" in $$source)) {
            this["ephemeral_1h_cost"] = 0;
        }
        if (!("total_cost" in $$source)) {
            this["total_cost"] = 0;
        }
        if (!("has_pricing" in $$source)) {
            this["has_pricing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReqeustLog instance from a string or object.
     */
    static createFrom($$source: any = {}): ReqeustLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReqeustLog($$parsedSource as Partial<ReqeustLog>);
    }
}

export class Skill {
    "key": string;
    "name": string;
    "description": string;
    "directory": string;
    "readme_url": string;
    "installed": boolean;
    "repo_owner"?: string;
    "repo_name"?: string;
    "repo_branch"?: string;

    /** Creates a new Skill instance. */
    constructor($$source: Partial<Skill> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("readme_url" in $$source)) {
            this["readme_url"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     */
    static createFrom($$source: any = {}): Skill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill($$parsedSource as Partial<Skill>);
    }
}

/**
 * UpdateInfo 更新信息
 */
export class UpdateInfo {
    "available": boolean;
    "version": string;
    "download_url": string;
    "release_notes": string;
    "file_size": number;
    "sha256": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("download_url" in $$source)) {
            this["download_url"] = "";
        }
        if (!("release_notes" in $$source)) {
            this["release_notes"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

/**
 * UpdateState 更新状态
 */
export class UpdateState {
    "last_check_time": time$0.Time;
    "last_check_success": boolean;
    "consecutive_failures": number;
    "latest_known_version": string;
    "download_progress": number;
    "update_ready": boolean;

    /**
     * 新增：持久化自动检查开关
     */
    "auto_check_enabled": boolean;

    /** Creates a new UpdateState instance. */
    constructor($$source: Partial<UpdateState> = {}) {
        if (!("last_check_time" in $$source)) {
            this["last_check_time"] = null;
        }
        if (!("last_check_success" in $$source)) {
            this["last_check_success"] = false;
        }
        if (!("consecutive_failures" in $$source)) {
            this["consecutive_failures"] = 0;
        }
        if (!("latest_known_version" in $$source)) {
            this["latest_known_version"] = "";
        }
        if (!("download_progress" in $$source)) {
            this["download_progress"] = 0;
        }
        if (!("update_ready" in $$source)) {
            this["update_ready"] = false;
        }
        if (!("auto_check_enabled" in $$source)) {
            this["auto_check_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateState instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateState($$parsedSource as Partial<UpdateState>);
    }
}

export class installRequest {
    "directory": string;
    "repo_owner": string;
    "repo_name": string;
    "repo_branch": string;

    /** Creates a new installRequest instance. */
    constructor($$source: Partial<installRequest> = {}) {
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("repo_owner" in $$source)) {
            this["repo_owner"] = "";
        }
        if (!("repo_name" in $$source)) {
            this["repo_name"] = "";
        }
        if (!("repo_branch" in $$source)) {
            this["repo_branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new installRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): installRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new installRequest($$parsedSource as Partial<installRequest>);
    }
}

export class skillRepoConfig {
    "owner": string;
    "name": string;
    "branch": string;
    "enabled": boolean;

    /** Creates a new skillRepoConfig instance. */
    constructor($$source: Partial<skillRepoConfig> = {}) {
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new skillRepoConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): skillRepoConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new skillRepoConfig($$parsedSource as Partial<skillRepoConfig>);
    }
}

// Private type creation functions
const $$createType0 = CLIConfigField.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CLIConfigFile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = ConfigImportStatus.createFrom;
const $$createType7 = LogStatsSeries.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = MCPServer.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $Create.Map($Create.Any, $Create.Any);
