// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 管理全局配置
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBlacklistLevelConfig 获取等级拉黑配置
 * 【修复】开关状态从数据库读取，其他配置从 JSON 文件读取
 */
export function GetBlacklistLevelConfig(): $CancellablePromise<$models.BlacklistLevelConfig | null> {
    return $Call.ByID(3210427164).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBlacklistSettings 获取黑名单配置
 */
export function GetBlacklistSettings(): $CancellablePromise<[number, number]> {
    return $Call.ByID(605514929);
}

/**
 * GetBlacklistSettingsStruct 获取黑名单配置（结构体形式，用于前端）
 */
export function GetBlacklistSettingsStruct(): $CancellablePromise<$models.BlacklistSettings | null> {
    return $Call.ByID(981449460).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetIntSetting 获取整数类型的配置值（通用方法）
 * 如果找不到或解析失败，返回 0
 */
export function GetIntSetting(key: string): $CancellablePromise<number> {
    return $Call.ByID(900230874, key);
}

/**
 * GetLevelBlacklistEnabled 获取等级拉黑开关状态
 */
export function GetLevelBlacklistEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(458497461);
}

/**
 * IsBlacklistEnabled 检查拉黑功能是否启用
 */
export function IsBlacklistEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3405992751);
}

/**
 * SaveBlacklistLevelConfig 保存等级拉黑配置
 */
export function SaveBlacklistLevelConfig(config: $models.BlacklistLevelConfig | null): $CancellablePromise<void> {
    return $Call.ByID(2798699223, config);
}

/**
 * SetIntSetting 设置整数类型的配置值（通用方法）
 */
export function SetIntSetting(key: string, value: number): $CancellablePromise<void> {
    return $Call.ByID(1050634246, key, value);
}

/**
 * SetLevelBlacklistEnabled 设置等级拉黑开关状态
 */
export function SetLevelBlacklistEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3234655753, enabled);
}

/**
 * UpdateBlacklistEnabled 更新拉黑功能开关
 */
export function UpdateBlacklistEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2636303210, enabled);
}

/**
 * UpdateBlacklistLevelConfig 更新等级拉黑配置
 */
export function UpdateBlacklistLevelConfig(config: $models.BlacklistLevelConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3815895291, config);
}

/**
 * UpdateBlacklistSettings 更新黑名单配置
 * 使用 Saga 模式保证数据一致性（因队列无法使用事务）
 */
export function UpdateBlacklistSettings(threshold: number, duration: number): $CancellablePromise<void> {
    return $Call.ByID(833260620, threshold, duration);
}

// Private type creation functions
const $$createType0 = $models.BlacklistLevelConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BlacklistSettings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
