// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService 更新服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyUpdate 应用更新（启动时调用）
 * 添加更新锁防止并发，SHA256 校验防止损坏文件
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(463634848);
}

/**
 * CheckUpdate 检查更新（带网络容错）
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3762820960).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckUpdateAsync 异步检查更新
 */
export function CheckUpdateAsync(): $CancellablePromise<void> {
    return $Call.ByID(3775462276);
}

/**
 * DownloadUpdate 下载更新文件（支持更新锁、重试、断点续传、SHA256校验）
 */
export function DownloadUpdate(progressCallback: any): $CancellablePromise<void> {
    return $Call.ByID(306369946, progressCallback);
}

/**
 * GetUpdateState 获取更新状态
 */
export function GetUpdateState(): $CancellablePromise<$models.UpdateState | null> {
    return $Call.ByID(1467420717).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * IsAutoCheckEnabled 是否启用自动检查
 */
export function IsAutoCheckEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1821512081);
}

/**
 * LoadState 加载状态
 */
export function LoadState(): $CancellablePromise<void> {
    return $Call.ByID(3886427880);
}

/**
 * PrepareUpdate 准备更新（公开方法，保留兼容性）
 * Deprecated: 建议使用 DownloadUpdate，它会自动调用内部 prepare 逻辑
 */
export function PrepareUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2497597027);
}

/**
 * RestartApp 重启应用
 * 如果有待安装的更新，会先触发更新流程（Windows 安装版会请求 UAC）
 */
export function RestartApp(): $CancellablePromise<void> {
    return $Call.ByID(1315746061);
}

/**
 * SaveState 保存状态（使用原子写入防止断电损坏）
 */
export function SaveState(): $CancellablePromise<void> {
    return $Call.ByID(2602461199);
}

/**
 * SetAutoCheckEnabled 设置是否启用自动检查
 */
export function SetAutoCheckEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(629868339, enabled);
}

/**
 * StartDailyCheck 启动每日8点定时检查
 * P1-3 修复：单次持锁完成检查+调度，消除竞态窗口
 */
export function StartDailyCheck(): $CancellablePromise<void> {
    return $Call.ByID(1615992142);
}

/**
 * StopDailyCheck 停止定时检查（公开方法，供外部调用）
 * P1-3 修复：对 dailyCheckTimer 访问加锁
 */
export function StopDailyCheck(): $CancellablePromise<void> {
    return $Call.ByID(3030210404);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UpdateState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
